### ISSUE TITLE
[16.0] [hr_attendance_report_theoretical_time] recompute theoretical attendance does not respect contractual hours

### ISSUE THREAD

**Issue by Highcooley** [OCA/hr-attendance#158]
## Module
hr_attendance_report_theoretical_time

## Describe the bug
When recomputing theoretical hours, the current resource_calendar is used to recompute the theoretical attendance, not respecting past contracts with different calendars.

## To Reproduce
**Affected versions**: 16.0

1. Create a contract valid in the past with e.g. 40h calendar
2. Create attendance entries in the period of the past contract
3. Create a second contract with e.g. 35h calendar
4. Create attendance entries in the period of the new contract
5. Recompute theoretical attendance in the period of both contracts

**Expected behavior**
Entries should respect the contractual resource_calendar of their period and only fall back on the current resource_calendar if no contract is available during the working period. 

**Additional context**
Also new entries in the past should respect the calendar which was valid during the time period.

**Comment by jschreiberc2c** [comment]
I have the same issue. Any news on this ticket?

**Comment by pedrobaeza** [comment]
This is something expected, as there's no info on which was the previous calendar. Use a module like `hr_employee_calendar_planning` for that.
