### ISSUE TITLE
[13.0][hr_attendance_report_theoretical_time] Theoretical hours as 0 if less than a day leave

### ISSUE THREAD

**Issue by ao-landoo** [OCA/hr-attendance#35]
When I ask for a leave which is for less than one day (half day checkbox DISABLED), and that leave is approved, I go to my attendandes -> hr.attendance.theoretical.time.report pivot view and the day I selected as a leave marks 0 theoretical hours.

Practical example:

I select a 0.5 days leave for 24th march (a day I should be working 8 hours). Then the theoretical hours field should me marking 4 hours, but it displays 0.

I attached two images so you can see the problem visually.

![peticion](https://user-images.githubusercontent.com/74420754/112496245-de514680-8d84-11eb-8f78-b8af208ff8f5.png)
![theo](https://user-images.githubusercontent.com/74420754/112496239-ddb8b000-8d84-11eb-9701-f3dc3111b74f.png)

**Comment by pedrobaeza** [comment]
Please don't ping us in issues. We receive them anyway.

We haven't faced such problem till now.
